name: Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
